version: "3.9"
services:

  postgresql.db.product.company.suffix:
    image: postgres:12.3
    container_name: postgresql.db.product.company.suffix
    hostname: postgresql.db.product.company.suffix
    volumes:
      - db.product.company.suffix:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-h", "postgresql.db.product.company.suffix", "-d", "product" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase.component.product.company.suffix:
    image: liquibase/liquibase:4.18
    container_name: liquibase.component.product.company.suffix
    command: --defaultsFile=/liquibase/config/liquibase.properties update
    depends_on:
      postgresql.db.product.company.suffix:
        condition: service_healthy

  schemaspy.component.product.company.suffix:
    image: schemaspy/schemaspy
    command: SCHEMASPY_OUTPUT=/schemaspy/component /usr/local/bin/schemaspy -schemas public,audit
    volumes:
      - schemaspy.component.product.company.suffix:/output:rw
    depends_on:
      liquibase.component.product.company.suffix:
        condition: service_completed_successfully

  www.schemaspy.component.product.company.suffix:
    image: nginx
    volumes:
      - schemaspy.component.product.company.suffix:/usr/share/nginx/html/component:ro
    depends_on:
      schemaspy.component.product.company.suffix:
        condition: service_completed_successfully

  component.product.company.suffix:
    build:
      context: .
    image: company.suffix/product/component:latest
    hostname: component.product.company.suffix
    depends_on:
      postgresql.db.product.company.suffix:
        condition: service_healthy
      liquibase.component.product.company.suffix:
        condition: service_completed_successfully

volumes:
  db.product.company.suffix: {}
  schemaspy.component.product.company.suffix: {}

