version: "3.9"
services:

  postgresql.db.product.company.suffix:
    ports:
      - "5432:5432"
    env_file:
      - conf/envs/db.env
    volumes:
      - ./conf/postgresql:/docker-entrypoint-initdb.d

  liquibase.component.product.company.suffix:
    volumes:
      - ./conf/liquibase/component-liquibase.properties:/liquibase/config/liquibase.properties
      - ./src/main/resources/db/changelog:/liquibase/changelog

  schemaspy.component.product.company.suffix:
    volumes:
      - ./conf/schemaspy/schemaspy.properties:/schemaspy.properties

  www.schemaspy.component.product.company.suffix:
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:80"

  component.product.company.suffix:
    env_file:
      - conf/envs/component.env
    ports:
      - "8080:8080"

volumes:
  schemaspy.component.product.company.suffix: {}

