# copy description from https://docs.spring.io/spring-boot/docs/2.7.3/reference/htmlsingle/#appendix.application-properties
# document env variable override for other users and devops
# try to use a flat structure so that it is easy to understand
# always document each configuration value, no exceptions.

# Application name.
spring.application.name: component

# The name of the application as displayed in the info actuator endpoint.
info.app.name: ${spring.application.name}

# A description of this application for the info actuator endpoint.
info.app.description: Spring Boot microservice reference architecture

# Controls how much git information to display in the actuator/info endpoint. Values are: simple or full
management.info.git.mode: simple

# Endpoint IDs that should be included or '*' for all.
management.endpoints.web.exposure.include: "*"

# When to show full health details.
management.endpoint.health.show-details: always

#spring.jpa.hibernate.ddl-auto: create

# JDBC URL of the database.
# override with env variable SPRING_DATASOURCE_URL
spring.datasource.url: jdbc:tc:postgresql:12.5://localhost:5432/postgres

# Login username of the database.
# override with env variable SPRING_DATASOURCE_USERNAME
spring.datasource.username: product

# Login password of the database.
# override with env variable SPRING_DATASOURCE_PASSWORD
spring.datasource.password: product

# Change log configuration path.
# override with env variable SPRING_LIQUIBASE_CHANGELOG
spring.liquibase.change-log: db/changelog/db.changelog-master.xml

# Whether to enable Liquibase support.
# override with env variable SPRING_LIQUIBASE_ENABLED
spring.liquibase.enabled: true

# Base path to be used by Spring Data REST to expose repository resources.
spring.data.rest.base-path: /data/rest/

# Flag that enables the springdoc-openapi endpoint.
# Turn this to false in production to disable swagger
# override with env variable SPRINGDOC_APIDOCS_ENABLED
springdoc.api-docs.enabled: true

# Don't cache API documentation.  That way, when the application is restarted,
# the API docs always reflect our latest annotation changes.  See
# https://springdoc.org/faq.html#_how_can_i_disable_springdoc_openapi_cache
# for more information.
springdoc.cache.disabled: true

# enable fully qualified names.
springdoc.use-fqn: true

#######################################################
# Do NOT add logging directives to this file.         #
#######################################################
# Instead, run the application with the logging settings enabled:
#
# $ ./gradlew bootRun --args='--logging.level.suffix.company=DEBUG'
